In [1]:
# @title Utilisation de l'API I
"""
from stackapi import StackAPI
import pandas as pd

SITE = StackAPI('stackoverflow')
questions = SITE.fetch('questions', tagged='python', min=50, sort='votes')

# Extract relevant data
data = [(item['creation_date'], item['title'], item['tags'], item['score']) for item in questions['items']]

# Create DataFrame
df = pd.DataFrame(data, columns=['Date', 'Title', 'Tags', 'Score'])

# Display DataFrame
df
"""

"\nfrom stackapi import StackAPI\nimport pandas as pd\n\nSITE = StackAPI('stackoverflow')\nquestions = SITE.fetch('questions', tagged='python', min=50, sort='votes')\n\n# Extract relevant data\ndata = [(item['creation_date'], item['title'], item['tags'], item['score']) for item in questions['items']]\n\n# Create DataFrame\ndf = pd.DataFrame(data, columns=['Date', 'Title', 'Tags', 'Score'])\n\n# Display DataFrame\ndf\n"

In [2]:
# @title Utilisation de l'API II

from stackapi import StackAPI
import pandas as pd

SITE = StackAPI('stackoverflow')

# Paramètres de recherche
params = {
    'min': 50,  # score min
    #'answers': 1,  # Au moins une réponse
    'tagged': 'python',
    'pagesize': 50 ,# Nombre de résultats
    #'max_pages' : 1 #Répété 1 fois
}

#SITE.max_pages = 1
#SITE.answers = 1
questions = SITE.fetch('questions', **params)

ids = []
titles = []
tags_list = []
view_counts = []
score_counts = []
#favorite_counts = []
answer_counts = []

for question in questions['items']:
    ids.append(question['question_id'])
    titles.append(question['title'])
    tags_list.append(', '.join(question['tags']))
    view_counts.append(question['view_count'])
    score_counts.append(question['score'])
    #favorite_counts.append(question['favorite_count'])
    answer_counts.append(question['answer_count'])

data = {
    'Id' : ids,
    'Titre': titles,
    'Tags': tags_list,
    'Nombre de vues': view_counts,
    'Score' : score_counts,
    #'Nombre de marquages favoris': favorite_counts,
    'Nombre de réponses': answer_counts
}

df = pd.DataFrame(data)
df

,Id,Titre,Tags,Nombre de vues,Score,Nombre de réponses
0,77626451,Filtering by JSON type field with Postgres and...,"python, postgresql, sqlalchemy",3,0,0
1,77626448,Python server using the socket module not work...,"python, sockets, server, connection, client",7,0,0
2,77626443,what are the challenges faced by cse students?,"javascript, python, html, computer-science, ra...",17,-4,0
3,77626039,How can i merge multiple excel files with mult...,"python, python-3.x, python-development-mode",19,0,1
4,77626069,How to query a JSONB column that has deeply ne...,"python, postgresql, sqlalchemy, fastapi",20,1,1
...,...,...,...,...,...,...
245,77624291,Support for cython speedups using PyDev in Ecl...,"python, python-3.x, eclipse, pydev",11,0,0
246,76540994,Google Analytics API Python &#39;ClientOptions...,"python, google-analytics-api, google-analytics-4",57,0,0
247,71201650,How to use selenium on Repl.it?,"python, selenium-webdriver, selenium-chromedri...",3264,3,2
248,77624120,google.api_core.exceptions.InvalidArgument: 40...,"python, cloud-document-ai",18,-1,0
249,77624206,HEROKU: FileNotFoundError: [Errno 2] No such f...,"python, flask, heroku",15,0,0